Add newsletter template for survey
dddseoul/dddseoul.github.io pull request #13
Opened 2024-10-07 14:32 UTC by level120

설문조사 뉴스레터 작성했습니다.

<img width="1170" alt="image" src="https://github.com/user-attachments/assets/ba7779dc-1418-4b24-8a8f-da287f0b62c9">

2024-10-07 14:34 UTC, level120 commented
#9 번 참고했습니다.

2024-10-07 23:28 UTC, justinyoo commented
이렇게 보입니다!

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/6fb4090f-5deb-4067-a863-8313037661af">

2024-10-07 23:31 UTC, level120 commented
> 이렇게 보입니다!
> 
> <img alt="image" width="1212" src="https://private-user-images.githubusercontent.com/1538528/374358191-6fb4090f-5deb-4067-a863-8313037661af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDQxNDcsIm5iZiI6MTcyODM0Mzg0NywicGF0aCI6Ii8xNTM4NTI4LzM3NDM1ODE5MS02ZmI0MDkwZi01ZGViLTQwNjctYTg2My04MzEzMDM3NjYxYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDdUMjMzMDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVjOTkwODcyZjBhMzY3N2EyZTNiNWI3OWY0ZTY5ZWY2YzA1MWY4YTYxMGEzYWRjYTViYmNmNDM5NmI0YWNhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JJwLkL6N0zSntof-d1dcBUNEBk-S1Vnnj1ZGwir3jwg">

오오 감사합니다! 의도한 대로 잘 렌더링 된 것 확인했습니다!

2024-10-07 23:33 UTC, justinyoo requested changes

2024-10-07 23:33 UTC, justinyoo commented on templates/newsletter-survey.md
> +의미 있는 답변을 모두 작성한 설문지 중에서 무작위로 당첨자를 선정합니다.
아시겠지만, 마크다운 문서에서는 줄바꿈이 의미가 있으려면 두줄 띄기를 해야 합니다. 그러면 그건 `<p>...</p>` 태그가 붙게 됩니다.

만약 여기서처럼 줄바꿈을 하려면 중간에 `<br>` 태그를 직접 넣어주셔야 해요.

`<br>`태그를 직접 넣는 것의 단점(?)이라면 실제로 보는 사람 입장에서는 의미없는 줄바꿈처럼 보일 수도 있습니다.

2024-10-07 23:33 UTC, justinyoo commented on templates/newsletter-survey.md
> +- 당첨자 경품 발송 예정일: 2024년 10월 21일 이후.
이 기간을 플레이스홀더로 할까요, 아니면 하드코딩을 할까요? 재활용 관점에서는 플레이스홀더가 맞지 싶습니다.

2024-10-07 23:35 UTC, level120 commented on templates/newsletter-survey.md
> +의미 있는 답변을 모두 작성한 설문지 중에서 무작위로 당첨자를 선정합니다.
한줄로 보이도록 의도한 것이긴 한데요, 별개 줄로 나누는 것이 좋을까요..? 기존 두 줄은 한번 더 띄우는 걸로 해서요
지금은 정말 줄 나눔이 필요한 곳에만 두 줄 띄우기 했었거든요.

2024-10-07 23:38 UTC, justinyoo commented on templates/newsletter-survey.md
> +의미 있는 답변을 모두 작성한 설문지 중에서 무작위로 당첨자를 선정합니다.
아, 그럼 여기서는 작성하는 사람의 가독성을 위한 줄바꿈이라고 이해하면 되는 거죠? 보는 사람은 원래대로 문단 하나로 보이는 게 정상이고?

2024-10-07 23:39 UTC, level120 commented on templates/newsletter-survey.md
> +의미 있는 답변을 모두 작성한 설문지 중에서 무작위로 당첨자를 선정합니다.
네네, 맞습니다!

2024-10-07 23:40 UTC, justinyoo commented
스타일 오타 난 것 수정해서 더 잘 보이게 수정했습니다. 그런데... 이렇게 왼쪽 정렬을 하는 의도 맞죠?

<img width="1105" alt="image" src="https://github.com/user-attachments/assets/c0345244-b9fc-4ae0-b907-2aacb0615ed4">

2024-10-07 23:42 UTC, level120 commented
> 스타일 오타 난 것 수정해서 더 잘 보이게 수정했습니다. 그런데... 이렇게 왼쪽 정렬을 하는 의도 맞죠?

넵! 맞습니다! 설문조사 버튼과 그 아래 개인정보보호 문구만 가운데 정렬하는 것으로 의도했어요!

2024-10-07 23:42 UTC, level120 commented on templates/newsletter-survey.md
> +- 당첨자 경품 발송 예정일: 2024년 10월 21일 이후.
수정했습니다!

2024-10-07 23:45 UTC, level120 commented on templates/newsletter-survey.md
> +- 당첨자 경품 발송 예정일: 2024년 10월 21일 이후.
아 렌더링을 안했네요.. 다시 올릴께요, 잠시만요!

2024-10-07 23:46 UTC, level120 commented on templates/newsletter-survey.md
> +- 당첨자 경품 발송 예정일: 2024년 10월 21일 이후.
html 파일까지 반영했습니다.

2024-10-07 23:49 UTC, level120 commented
> > 스타일 오타 난 것 수정해서 더 잘 보이게 수정했습니다. 그런데... 이렇게 왼쪽 정렬을 하는 의도 맞죠?
> 
> 넵! 맞습니다! 설문조사 버튼과 그 아래 개인정보보호 문구만 가운데 정렬하는 것으로 의도했어요!

아 스크린 샷을 보니 개인정보보호 문구도 왼쪽으로 되어 있네요;; 이제 출근이라 저녁에 다시 확인해볼꼐요 ㅠㅠ

2024-10-07 23:51 UTC, justinyoo commented
요렇게 나옵니다:

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/0e689dda-26ba-4de1-b995-5afa98ea3b6a">

아... 이거 어떻게 스샷 따서 올리는 거 자동화 안되나;;;

2024-10-08 13:45 UTC, level120 commented
가운데 정렬이 먹지 않은 문구는 개인정보보호정책 링크가 별도로 달려 있기에 제거했습니다.

이 양식의 일정은 ASAP였기 때문에 특별한 이견이 없다면 가능한 빨리 머지되어 발송하면 좋을 것 같습니다.

2024-10-08 23:09 UTC, justinyoo approved these changes
머지하겠습니다!

2024-10-08 23:10 UTC, merged