Add CFP 결과 메일
dddseoul/dddseoul.github.io pull request #19
Opened 2024-11-05 15:41 UTC by level120

6일에 발송할 CFP 메일 내용입니다. 피드백 주시면 저녁에 퇴근 후 일괄 수정하겠습니다.

2024-11-05 23:22 UTC, ppiyakk2 requested changes

2024-11-05 23:22 UTC, ppiyakk2 commented on templates/cfp-accepted.html
> +<p>본 메일은 DDD Seoul 2024 행사에 발표자로 선정되신 분들께 숨은 참조로 발송하였습니다.</p>
숨은 참조 발송은 때에 따라 발표자가 인지하지 못하는 경우가 있었습니다.

개별발송하는 것이 좋겠습니다. outlook에 복수의 대상자에게 개별메일 발송이 있으면 좋겠네요..

2024-11-05 23:22 UTC, ppiyakk2 commented on templates/cfp-accepted.html
> +<p>최종 발표자로 등록하기 위해 본 메일을 <span style="color:#AC4E21">11월 8일 23:59</span>까지 회신하여 주십시오.</p>
발표 여부를 확정하기 위해

2024-11-05 23:22 UTC, ppiyakk2 commented on templates/cfp-accepted.html
> +<p>그룹에서 검토한 결과, 지원자님께서 제출해주신 내용이 정말 훌륭하여 이번 <span style="color:#AC4E21">[DDD Seoul 2024]</span>에 발표자로 선정하였습니다!</p>
제안한 발표 제목을 같이 적어주면 좋습니다.

2024-11-05 23:22 UTC, ppiyakk2 commented on templates/cfp-pending.html
> +<p>본 메일은 DDD Seoul 2024 행사에 예비 발표자로 선정되신 분들께 숨은 참조로 발송하였습니다.</p>
마찬가지로 개별발송

2024-11-05 23:22 UTC, ppiyakk2 commented on templates/cfp-pending.html
> +<p>다만, 지원자님께서는 제출해주신 내용이 정말 훌륭하여 앞서 선정된 발표자분이 취소할 경우 기회를 받으실 수 있도록 <span style="color:#AC4E21">예비 발표자</span>로 선정하였습니다.</p>
이 내용 아래에 제안한 발표 제목을 추가해주세요

2024-11-05 23:22 UTC, ppiyakk2 commented on templates/cfp-pending.html
> +<p><span style="color:#AC4E21">예비 발표자</span> 선정 결과는 기회가 생길 경우 실시간으로 전달할 예정이며 우선적으로 11일까지 연락드릴 예정입니다. 그러나 이날까지 연락을 받지 못했더라도 추후에 상황이 변경되면 발표자 제안이 갈 수 있으니 참고 부탁드립니다.</p>
예비발표자가 무엇인지 추가설명이 필요합니다

2024-11-05 23:22 UTC, ppiyakk2 commented on templates/cfp-reject.html
> +<p>혹시 이번 발표 제안 관정 중 의도하지 않게 불편을 드린 점은 없었는지 여러모로 마음이 쓰입니다.</p>
제안 과정 중 / 오타 수정

앞에 너무 많은 머리글이 있어서 한 줄로 줄이고 결과를 바로 안내하는게 좋겠습니다 

핵심을 바로 전달하는게 가독성이 높았습니다

2024-11-05 23:33 UTC, level120 commented on templates/cfp-accepted.html
> +<p>본 메일은 DDD Seoul 2024 행사에 발표자로 선정되신 분들께 숨은 참조로 발송하였습니다.</p>
이건 방법 좀 찾아볼께요, 가능할 지요

2024-11-05 23:37 UTC, justinyoo requested changes
전체적인 톤을 낮추고, 보내는 사람 관점 보다는 읽는 사람 관점에서 보면 어떨까 싶어서 코멘트 남겨뒀습니다.

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-accepted.md
> +> 본 메일은 DDD Seoul 2024 행사에 발표자로 선정되신 분들께 숨은 참조로 발송하였습니다.
파워오토메이트로 개인화 이메일을 보낼 예정이므로 굳이 이 라인은 필요없습니다

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-accepted.md
> +그룹에서 검토한 결과, 지원자님께서 제출해주신 내용이 정말 훌륭하여 이번 <span style="color:#AC4E21">[DDD Seoul 2024]</span>에 발표자로 선정하였습니다!
톤이 좀 권위적인 것 같은데, 그냥

> {{SPEAKER}}님의 세션, "{{SESSION_TITLE}}"을/를 DDD Seoul에서 청중들과 공유할 수 있게 되어 너무나도 기쁩니다.

쯤이면 어떨까요?

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-accepted.md
> +최종 발표자로 등록하기 위해 본 메일을 <span style="color:#AC4E21">11월 8일 23:59</span>까지 회신하여 주십시오.
1. 11월 8일 밤 12시 (12월 9일 0시) 라고 명시해 주시면 좋겠습니다.
2. 이메일 기능 중에서 [발표자 선정 확인했습니다][발표 취소하겠습니다] 같은 버튼을 눌러 사용자 액션을 요구하는 기능이 있어요. 이거 파워오토메이트로 구현 가능한지 확인해 보겠습니다. 이에 맞춰서

  > ...까지 위의 액션 버튼을 눌러 발표자 참여 여부를 확인해 주세요.

같은 식으로 수정해야 할 듯?

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-accepted.md
> +내용은 <span style="color:#AC4E21">"확인하였습니다"</span>와 같은 짧은 메시지여도 상관없습니다.
그렇다면 이 라인은 필요 없겠죵

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-accepted.md
> +만약 사정이 생겨 발표를 취소해야 하는 경우에도 메일 회신으로 안내 부탁드립니다.
> 혹시나 이후에 발표 관련 변경사항이 있을 경우 이 메일로 꼭 회신 부탁 드립니다.

쯤이면 어떨까요?

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-accepted.md
> +이 절차는 DDD Seoul이 지원자님을 발표자로 선정한 뒤, 지원자님께서 최종적으로 이 행사에 참여한다는 것을 확인하기 위함이니 꼭 본 메일을 회신해주십시오.
이 문장은 필요없지 싶구요

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-accepted.md
> +만약 지정된 기한까지 회신하지 않으실 경우 최종적으로 지원자님께서는 발표자 선정에서 탈락 처리하며 예비 순위인 분께 발표 기회가 넘어갑니다.
> 만약 지정된 기한까지 회신하지 않으실 경우 다음 순위 발표자에게 발표 기회가 넘어갑니다.

쯤으로 하면 될 듯?

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-pending.md
> +> 본 메일은 DDD Seoul 2024 행사에 예비 발표자로 선정되신 분들께 숨은 참조로 발송하였습니다.
파워오토메이트로 개인화 이메일을 보낼 예정이므로 굳이 이 라인은 필요없습니다

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-pending.md
> +이는 한정된 자리 대비 많은 분들께서 지원을 해주셨기에 모든 분들께 기회를 드릴 수 없었던 점 양해 부탁드립니다.
> 기대치를 훨씬 웃도는 숫자의 발표 제안서와 더불어 보내주신 모든 내용들이 정말로 매력적이었는지라 선정하기가 너무나도 힘들었습니다.
> 
> 지원해주신 모든 분들께 기회를 드리고 싶었으나, 발표 세션의 숫자가 제한적인지라 안타깝게도 간발의 차이로 {{SPEAKER}}님의 세션, "{{SESSION_TITLE}}"을/를 DDD Seoul에서 일차적으로 모실 수 없게 됐습니다만, 혹시나 현재 최종 발표자 구성에 변동이 생길 경우 우선적으로 {{SPEAKER}}님의 세션을 고려할 예정입니다.
> 
> 후속 이메일을 기다려 주시구요, 그 때 발표자 참여 여부를 다시 여쭙겠습니다.

쯤으로 하면 어떨까요?

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-pending.md
> +먼저 <span style="color:#AC4E21">[DDD Seoul 2024]</span> 컨퍼런스에 발표할 주제를 신청해 주셔서 진심으로 감사합니다.
감사합니다 👉 고맙습니다

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-reject.md
> +> 본 메일은 DDD Seoul 2024 행사에 발표자로 선정되지 못한 분들께 숨은 참조로 발송하였습니다.
파워오토메이트로 개인화 이메일을 보낼 예정이므로 굳이 이 라인은 필요없습니다

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-reject.md
> +먼저 <span style="color:#AC4E21">[DDD Seoul 2024]</span> 컨퍼런스에 발표할 주제를 신청해 주셔서 진심으로 감사합니다.
감사합니다 👉 고맙습니다

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-reject.md
> +이는 한정된 자리 대비 많은 분들께서 지원을 해주셨기에 모든 분들께 기회를 드릴 수 없었던 점, 더불어 한 분 한 분께 개별적인 피드백을 드리지 못하는 점 양해 부탁드립니다.
> 기대치를 훨씬 웃도는 숫자의 발표 제안서와 더불어 보내주신 모든 내용들이 정말로 매력적이었는지라 선정하기가 너무나도 힘들었습니다.
> 
> 지원해주신 모든 분들께 기회를 드리고 싶었으나, 발표 세션의 숫자가 제한적인지라 안타깝게도 간발의 차이로 {{SPEAKER}}님의 세션, "{{SESSION_TITLE}}"을/를 DDD Seoul에서 일차적으로 모실 수 없게 됐습니다.
> 

쯤이면 어떨까요?

2024-11-05 23:37 UTC, justinyoo commented on templates/cfp-reject.md
> +꼭 참가자로 오셔서 이번 행사를 함께 즐기실 수 있기를 바랍니다.
> 그러나 발표자로 참여하시지는 못하시더라도 DDD Seoul에 꼭 오셔서 다른 세션들을 함께 즐길 수 있기를 희망합니다!

쯤이면 어떨까요?

2024-11-06 13:13 UTC, level120 commented on templates/cfp-accepted.md
> +<!-- 제출 결과: {{SESSION_TITLE}} - 응답 필요! -->
각 마크다운 파일의 최상단에 있는 여기는 예상하는 메일 제목입니다.

2024-11-06 13:21 UTC, level120 commented on templates/cfp-accepted.md
> +(이 링크는 12월 9일 0시까지만 유효합니다)
헐.. 중요한 오타 발견했네요, 수정할께요

2024-11-06 14:29 UTC, justinyoo approved these changes

2024-11-06 14:29 UTC, merged